---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dockerfile dependencies"
  - package-ecosystem: "pip"
    directory: "/.github/workflows/support/matrix"  # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - "pip dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"  # Workflow files stored in the default location of `.github/workflows`
    schedule:
      interval: "daily"
    labels:
      - "github actions"
