name: notify

on:
  schedule:
    - cron: '3 5 * * *'

defaults:
  run:
    shell: bash

jobs:

  compose_latest:
    name: Query versions in the docker-compose.yml file
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Get .services.dhis2.image from docker-compose.yml
        id: yq
        uses: mikefarah/yq@915e9de437b645435e004ef13c5dc347f855658d
        with:
          cmd: yq eval .services.dhis2.image docker-compose.yml
      - name: Query version of DHIS2
        id: dhis2
        run: |
          set -x
          echo "::set-output name=version::$( awk -F'[}-]' '{print $(NF-1)}' <<<'${{ steps.yq.outputs.result }}' )"
    outputs:
      dhis2: ${{ steps.dhis2.outputs.version }}

  env_example:
    name: Query versions in .env.example
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Query version of DHIS2
        id: dhis2
        run: |
          set -x
          echo "::set-output name=version::$( source .env.example && echo "$DHIS2_TAG" )"
      - name: Query version of Tomcat
        id: tomcat
        run: |
          set -x
          echo "::set-output name=version::$( grep --only-matching --extended-regexp 'tomcat[0-9]{1,2}\.[0-9.]+' .env.example | sed 's/^tomcat//' )"
    outputs:
      dhis2: ${{ steps.dhis2.outputs.version }}
      tomcat: ${{ steps.tomcat.outputs.version }}

  image_latest:
    name: Query versions in the latest ghcr.io/baosystems/dhis2 image
    runs-on: ubuntu-20.04
    container: ghcr.io/baosystems/dhis2:latest
    steps:
      - name: Query version of DHIS2
        id: dhis2
        run: |
          set -x
          echo "::set-output name=version::$( awk -F'=' '/^build\.version/ {gsub(/ /, "", $NF); print $NF}' /opt/dhis2/build.properties )"
      - name: Query version of Tomcat
        id: tomcat
        run: |
          set -x
          echo "::set-output name=version::$TOMCAT_VERSION"
    outputs:
      dhis2: ${{ steps.dhis2.outputs.version }}
      tomcat: ${{ steps.tomcat.outputs.version }}

  notify:
    name: Notify of dependencies that need to be updated
    needs:
      - compose_latest
      - env_example
      - image_latest
    runs-on: ubuntu-20.04
    steps:
      - name: Send message to Slack about DHIS2_TAG in docker-compose.yml
        if: ${{ needs.compose_latest.outputs.dhis2 != needs.image_latest.outputs.dhis2 }}
        uses: slackapi/slack-github-action@410ae57cff5c6b682b106440be0e6c7eb8c98c9d
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: "{\"level\": \":warning: WARNING\", \"message\": \"DHIS2_TAG in docker-compose.yml (${{ needs.compose_latest.outputs.dhis2 }}) does not match version in ghcr.io/baosystems/dhis2:latest (${{ needs.image_latest.outputs.dhis2 }})\"}"
      - name: Send message to Slack about DHIS2_TAG in .env.example
        if: ${{ needs.env_example.outputs.dhis2 != needs.image_latest.outputs.dhis2 }}
        uses: slackapi/slack-github-action@410ae57cff5c6b682b106440be0e6c7eb8c98c9d
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: "{\"level\": \":warning: WARNING\", \"message\": \"DHIS2_TAG in .env.example (${{ needs.env_example.outputs.dhis2 }}) does not match version in ghcr.io/baosystems/dhis2:latest (${{ needs.image_latest.outputs.dhis2 }})\"}"
      - name: Send message to Slack about Tomcat version in .env.example
        if: ${{ needs.compose_latest.outputs.tomcat != needs.image_latest.outputs.tomcat }}
        uses: slackapi/slack-github-action@410ae57cff5c6b682b106440be0e6c7eb8c98c9d
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: "{\"level\": \":warning: WARNING\", \"message\": \"Tomcat version in .env.example (${{ needs.env_example.outputs.tomcat }}) does not match version in ghcr.io/baosystems/dhis2:latest (${{ needs.image_latest.outputs.tomcat }})\"}"
